language: csharp
dist: xenial
sudo: required
mono: none
dotnet: 3.1
branches:
    only:
        - master
before_script:
    - chmod -R 777 ./ci/
script:
    - ./ci/build.sh
    - ./ci/test.sh
notifications:
    email:
        - on_success: always
        - on_failure: always
