language: csharp
dist: trusty
sudo: required
mono: none
dotnet: 2.1.2
branches:
    only:
        - master
before_script:
    - chmod 777 ./travis-build-test.sh
script:
    - dotnet restore ./FileParserSolution
    - dotnet build ./FileParserSolution
    - ./travis-build-test.sh
notifications:
    email:
        - on_success: always
        - on_failure: always