language: csharp
dist: xenial
sudo: required
mono: none
dotnet: 2.2
branches:
    only:
        - master
before_script:
    - chmod -R 777 ./ci/
script:
    - ./build.sh
    - ./test.sh
notifications:
    email:
        - on_success: always
        - on_failure: always
