language: csharp
os:
- linux
- osx
- windows
dist: bionic
sudo: required
mono: none
dotnet: 3.1
script:
    - dotnet restore
    - dotnet build --no-restore -c Release /p:DeterministicBuild=true
    - dotnet test --no-build -c Release --logger trx --collect "Code coverage"
    - revision=${TRAVIS_JOB_ID:=1}
    - revision=$(printf "%04d" $revision)
notifications:
    email:
        - on_failure: always