language: csharp
dist: xenial
sudo: required
mono: none
dotnet: 2.2
branches:
    only:
        - master
before_script:
    - chmod 777 ./ci/travis-build.sh
    - chmod 777 ./ci/travis-test.sh
script:
    - (cd ci; ./travis-build.sh)
    - (cd ci; ./travis-test.sh)
notifications:
    email:
        - on_success: always
        - on_failure: always
