name: $(BuildID)

trigger:
  branches:
    include:
    - master

schedules:
- cron: "1 0 * * 1"
  displayName: 'Weekly build'
  always: true
  branches:
    include:
    - master

variables:
  SdkVersion: '3.1.x'

stages:
- stage: CI
  displayName: 'Build and run tests'
  jobs:
  - job: ci
    displayName: 'Build and run tests'

    strategy:
      maxParallel: 3
      matrix:
        linux:
          imageName: 'ubuntu-latest'
        mac:
          imageName: 'macOS-latest'
        windows:
          imageName: 'windows-latest'
    pool:
      vmImage: $(imageName)

    variables:
      disable.coverage.autogenerate: 'true'
      EscapedComma: '%2c'
      TestResults: '$(Agent.TempDirectory)'
      CoverageResults: '$(Build.SourcesDirectory)/CoverageResults'

    steps:
    - task: UseDotNet@2
      displayName: 'Use .NET Core sdk v$(SdkVersion)'
      inputs:
        packageType: sdk
        version: '$(SdkVersion)'

    - task: SonarCloudPrepare@1
      displayName: 'Prepare SonarCloud analysis'
      condition: eq(variables['imageName'], 'windows-latest')
      inputs:
        SonarCloud: 'FileParser_SonarCloud'
        organization: 'eduherminio-github'
        scannerMode: 'MSBuild'
        projectKey: 'FileParser'
        projectName: 'FileParser'
        extraProperties: |
            sonar.cs.opencover.reportsPaths="$(Build.SourcesDirectory)/**/coverage.opencover.xml"
            sonar.cs.vstest.reportsPaths="$(TestResults)/**/*.trx"

    - task: DotNetCoreCLI@2
      displayName: 'Build'
      inputs:
        command: build
        arguments: '--configuration Release'
        projects: './src/FileParserSolution.sln'

    - task: DotNetCoreCLI@2
      displayName: 'Run tests'
      inputs:
        command: test
        arguments: >-
            --configuration Release --no-build
            /p:CollectCoverage=true /p:CoverletOutputFormat="cobertura$(EscapedComma)opencover"
            /p:CoverletOutput=./CoverageResults/ /p:ExcludeByFile="**/*Exception.cs$(EscapedComma)**/*Test.cs"
        nobuild: true
        projects: '**/FileParser.Test.csproj'
        publishTestResults: true

    - task: Palmmedia.reportgenerator.reportgenerator-build-release-task.reportgenerator@4
      displayName: 'Generate tests report'
      condition: eq(variables['imageName'], 'ubuntu-latest')
      inputs:
        reports: '$(Build.SourcesDirectory)/**/coverage.cobertura.xml'
        targetdir: '$(CoverageResults)'
        reporttypes: 'HtmlInline_AzurePipelines;Cobertura;Badges'
        assemblyfilters: '-xunit*'

    - task: PublishCodeCoverageResults@1
      displayName: 'Publish code coverage'
      condition: eq(variables['imageName'], 'ubuntu-latest')
      inputs:
        codeCoverageTool: Cobertura
        summaryFileLocation: '$(CoverageResults)/Cobertura.xml'
        reportDirectory: '$(CoverageResults)'
        pathToSources: '$(Build.SourcesDirectory)'

    - task: SonarCloudAnalyze@1
      displayName: 'Perform SonarCloud analysis'
      condition: eq(variables['imageName'], 'windows-latest')

    - task: SonarCloudPublish@1
      displayName: 'Publish SonarCloud analysis'
      condition: eq(variables['imageName'], 'windows-latest')
      inputs:
        pollingTimeoutSec: '300'

- stage: CD
  displayName: 'Generate package(s)'
  dependsOn: 'CI'
  condition: and(succeeded('CI'), eq(variables['Build.SourceBranch'], 'refs/heads/master'))
  jobs:
  - job: cd
    displayName: 'Generate package(s)'
    pool:
      vmImage: ubuntu-latest
    steps:

    - checkout: self
      persistCredentials: true
      clean: true

    - task: UseDotNet@2
      displayName: 'Use .NET Core sdk v$(SdkVersion)'
      inputs:
        packageType: sdk
        version: '$(SdkVersion)'

    - task: NuGetToolInstaller@1
      displayName: 'Setup NuGet'
      inputs:
        versionSpec: '5.3.1'
        checkLatest: true

    - task: CmdLine@2
      displayName: 'Setup Git'
      inputs:
        workingDirectory: $(Build.SourcesDirectory)
        script: |
            git config --replace-all user.email "azure@devops.com"
            git config --replace-all user.name "Azure DevOps"

    - task: DotNetCoreCLI@2
      displayName: 'Build'
      inputs:
        command: build
        arguments: '--configuration Release /p:ContinuousIntegrationBuild=true'
        projects: './src/FileParserSolution.sln'

    - task: DotNetCoreCLI@2
      displayName: 'Modify project version'
      condition: ne(variables['PackageVersion'], '')
      inputs:
        command: build
        arguments: '--configuration Release /t:ReplaceVersion /p:VersionTag=$(PackageVersion)'
        projects: '**/FileParser.csproj'

    - task: DotNetCoreCLI@2
      displayName: 'Generate NuGet package'
      inputs:
        command: 'pack'
        arguments: '--configuration Release'
        configuration: 'Release'
        packagesToPack: '**/FileParser.csproj'
        nobuild: true
        packDirectory: '$(Build.SourcesDirectory)/Artifacts'

    - task: PublishBuildArtifacts@1
      displayName: 'Publish artifact with NuGet package and its symbols'
      inputs:
        pathtoPublish: '$(Build.SourcesDirectory)/Artifacts/'
        artifactName: 'FileParser'

    - task: DotNetCoreCLI@2
      displayName: 'Test Nuget package locally'
      inputs:
        command: test
        arguments: '--configuration Release --logger trx"'
        nobuild: true
        projects: '**/*NugetTest.csproj'

    - task: NuGetCommand@2
      displayName: 'Push NuGet package'
      condition: ne(variables['PackageVersion'], '')
      inputs:
        command: 'push'
        packagesToPush: '$(Build.SourcesDirectory)/Artifacts/*.nupkg'
        nuGetFeedType: 'external'
        publishFeedCredentials: 'FileParser_NuGet'
        verbosityPush: 'Detailed'

    - task: NuGetCommand@2
      displayName: 'Push GitHub package'
      condition: ne(variables['PackageVersion'], '')
      inputs:
        command: 'push'
        packagesToPush: '$(Build.SourcesDirectory)/Artifacts/*.nupkg'
        nuGetFeedType: 'external'
        publishFeedCredentials: 'GitHubPackageRegistry'
        verbosityPush: 'Detailed'

    - task: CmdLine@2
      displayName: 'Commit and push version increment'
      condition: and(eq(variables['NoCommit'], ''), ne(variables['PackageVersion'], ''))
      inputs:
        workingDirectory: $(Build.SourcesDirectory)
        script: |
          git checkout master
          git status
          git add -A
          git commit -m "Release v$(PackageVersion)"
          git tag -a v$(PackageVersion) -m "v$(PackageVersion)"
          git push
          git push --tags
