name: CI

on:
  push:
  pull_request:
  schedule:
    - cron:  '1 0 * * 1'    # * is a special character in YAML, therefore this string needs to be quoted

jobs:
  build:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macOS-latest]
      fail-fast: false

    env:
      DOTNET_CLI_TELEMETRY_OPTOUT: 1
      ARTIFACT_DIR: ./Artifacts

    steps:
    - uses: actions/checkout@v2.3.3

    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1.7.2
      with:
        dotnet-version: 5.0.100

    - name: '[Ubuntu] Set version to -ci-${{ github.run_number }}'
      if: matrix.os == 'ubuntu-latest'
      shell: pwsh
      run: |
        $input_path = "src/FileParser/FileParser.csproj"
        $regex = "(?<=<Version>).*(?=</Version>)"
        (Get-Content $input_path) -Replace $regex, '$0-ci-${{ github.run_number }}' | Out-File $input_path

    - name: Build
      run: dotnet build -c Release /p:DeterministicBuild=true

    - name: Run tests
      run: dotnet test -c Release --no-build

    - name: '[Ubuntu] Pack'
      if: matrix.os == 'ubuntu-latest'
      run: |
        dotnet pack -c Release --no-build src/FileParser/FileParser.csproj --include-symbols -o ${{ env.ARTIFACT_DIR }}

    - name: '[Ubuntu] Upload Artifact'
      if: matrix.os == 'ubuntu-latest'
      uses: actions/upload-artifact@v2
      with:
        name: FileParser-ci-artifact
        path: |
          ${{ env.ARTIFACT_DIR }}/*.nupkg
          ${{ env.ARTIFACT_DIR }}/*.snupkg
        if-no-files-found: error
