name: CI GitHub Actions

on:
  push:
    branches:
    - master
  pull_request:
    branches:
    - master
  schedule:
    # * is a special character in YAML so you have to quote this string
    - cron:  '* * * * 1

jobs:
  build:

    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [macOS-latest, ubuntu-latest]
        # Windows excluded due to problems with bash building scripts
      fail-fast: false

    steps:
    - uses: actions/checkout@v1
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 2.2.108
    - name: Give permissions to CI scripts
      run: chmod -R 777 ./ci/
    - name: Build
      run: ./ci/build.sh
    - name: Run tests
      run: ./ci/test.sh
